services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    ports:
      - 8090:8090/tcp
    volumes:
      - ./opt/gluetun:/gluetun
      - ./opt/gluetun/wg0.conf:/gluetun/wireguard/wg0.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,172.16.0.0/12,172.17.0.0/16
    restart: always

  torrserver:
    image: ubuntu:22.04
    container_name: torrserver
    network_mode: service:gluetun
    depends_on:
      gluetun: {condition: service_healthy}
    volumes:
      - ./opt/torrserver/bin/TorrServer:/usr/local/bin/TorrServer:ro
      - ./opt/torrserver/db:/db
    environment:
      - TS_LOGIN=${TS_USER}
      - TS_PASSWORD=${TS_PASS}
    command: >
      sh -c "apt-get update && apt-get install -y ca-certificates && 
      /usr/local/bin/TorrServer --port 8090 --path /db --httpauth"
    restart: unless-stopped
