services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    ports:
      - 8090:8090/tcp
    volumes:
      - ./opt/gluetun/wg0.conf:/gluetun/wireguard/wg0.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,172.16.0.0/12,172.17.0.0/16
    restart: always

  torrserver:
    image: ubuntu:22.04
    container_name: torrserver
    network_mode: service:gluetun
    depends_on:
      gluetun: {condition: service_healthy}
    volumes:
      - ./opt/torrserver/bin/TorrServer:/usr/local/bin/TorrServer:ro
      - ./opt/torrserver/db:/db
      - ./opt/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    # Мы используем универсальное имя TorrServer, которое скрипт даст бинарнику при скачивании
    command: /usr/local/bin/TorrServer --port 8090 --path /db --httpauth
    restart: unless-stopped
